ALTER TABLE periodtracker.oky_user
ADD COLUMN score_kespro VARCHAR(255) DEFAULT NULL,
ADD COLUMN score_keswa VARCHAR(255) DEFAULT NULL,
ADD COLUMN score_who5 VARCHAR(255) DEFAULT NULL,
ADD COLUMN score_imt VARCHAR(255) DEFAULT NULL;
